title: AritMetricaMENTE
description: Evaluación e intervención psicológia basada en la evidencia, fundamentada en el análisis del comportamiento, la psicometría y la ciencia de datos.
theme: jekyll-theme-cayman # Un tema limpio, moderno y profesional
url: "https://aritmetricamente.com"
